import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}

      >
        <header className=" bg-white shadow-md sticky z-50 top-0">
        <div className="container mx-auto px-4 py-6 flex justify-between items-center">
          <h1 className="text-3xl font-bold text-gray-800">AI Travel Planner</h1>
          <nav>
            <ul className="flex space-x-4">
              <li><Link href="/" className="text-gray-600 hover:text-[#fc5071]">Home</Link></li>
              <li><Link href="/form" className="text-gray-600 hover:text-[#fc5071]">Plan a Trip</Link></li>
              <li><Link href="/about" className="text-gray-600 hover:text-[#fc5071]">About</Link></li>
              <li><Link href="/login" className="text-gray-600 hover:text-[#fc5071]">Contact</Link></li>
            </ul>
          </nav>
        </div>
      </header>
        {children}
        <footer className="bg-gray-800 text-white py-8">
        <div className="container mx-auto px-4">
          <div className="flex flex-wrap justify-between">
            <div className="w-full md:w-1/3 mb-6 md:mb-0">
              <h3 className="text-xl font-semibold mb-2">AI Travel Planner</h3>
              <p className="text-gray-400">Your intelligent companion for unforgettable journeys.</p>
            </div>
            <div className="w-full md:w-1/3 mb-6 md:mb-0">
              <h4 className="text-lg font-semibold mb-2">Quick Links</h4>
              <ul className="text-gray-400">
                <li><Link href="#" className="hover:text-[#fc5071]">About Us</Link></li>
                <li><Link href="#" className="hover:text-[#fc5071]">FAQs</Link></li>
                <li><Link href="#" className="hover:text-[#fc5071]">Privacy Policy</Link></li>
                <li><Link href="#" className="hover:text-[#fc5071]">Terms of Service</Link></li>
              </ul>
            </div>
            <div className="w-full md:w-1/3">
              <h4 className="text-lg font-semibold mb-2">Connect With Us</h4>
              <ul className="text-gray-400">
                <li><Link href="#" className="hover:text-[#fc5071]">Facebook</Link></li>
                <li><Link href="#" className="hover:text-[#fc5071]">Twitter</Link></li>
                <li><Link href="#" className="hover:text-[#fc5071]">Instagram</Link></li>
                <li><Link href="#" className="hover:text-[#fc5071]">LinkedIn</Link></li>
              </ul>
            </div>
          </div>
          <div className="mt-8 text-center text-gray-400">
            <p>&copy; 2024 AI Travel Planner. All rights reserved.</p>
          </div>
        </div>
      </footer>
      </body>
    </html>
  );
}
